# MongoDB configuration
MONGO_URI = "mongodb://localhost:27017/task_manager_db"

# JWT secret key
JWT_SECRET_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5MzQwODQzNywianRpIjoiYjFlY2VkZmUtNTU2Yi00YWMxLWI4ZDAtZjJhMjMyYWNhZGIwIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3RfdXNlciIsIm5iZiI6MTY5MzQwODQzNywiZXhwIjoxNjkzNDA5MzM3fQ.Vbl5twA9fsRYOV3JPwgXM7dcAGYg57JwblTeGTGM2bA"
